### ISSUE TITLE
compare_EKF_UKF_Multilat_TS_Trilat_demo_SportHall_40x20

### ISSUE THREAD

**Issue by Minghua-Andrew** [cliansang/positioning-algorithms-for-uwb-matlab#2]
Hello,May I ask a question?, that is, in the algorithm I asked for help (compare_EKF_UKF_Multilat_TS_Trilat_demo_SportHall_40x20) is it only the (TRILATERATION ALGORITHM USING MEASURED RANGES) algorithm that utilizes only the three flight distances A0,A1,A2; the other four algorithms utilize the four flight distances i.e. A0,A1,A1,A2 when solving for the coordinates. ) This algorithm utilizes only the A0,A1,A2 flight distances; do the other four algorithms utilize the four A0,A1,A2,A3 flight distances when solving for the coordinates? Because my current A3 coordinate measurements are not very accurate, this is what is bothering me at the moment. Looking forward to your reply, best wishes!

**Comment by cliansang** [comment]
As the name implies, Trilateration algorithm uses only three ranges in the estiamtion process of target position (i.e., measured ranges from a tag to anchor A0, A1, and A2 in in this repo as you correctly stated.). The other four algorithms use all availalbe measurement (i.e., measured ranged from a tag to A0, A1, A2 and A3 in this repo due to the provided measurement scenario). However, it should be noted that there is no limit to the measured ranges to be handled for the positioning algorithm except for Trilateration.
